#!/usr/bin/env bash
# Configures an Ubuntu server with respet to local host
# and Fasebook

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
