#!/usr/bin/env bash
#Bash script that uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu

SERVER_ADDRESS="35.153.98.242"

ssh -i ~/.ssh/school ubuntu@$SERVER_ADDRESS
