#!/usr/bin/env bash
# bash to create RSA pair keys.

KEY_NAME="school"
KEY_BITS=4096
PASSPHRASE="betty"
EMAIL="memo12317emad@gmail.com"

ssh-keygen -t rsa -b $iKEY_BITS -N $PASSPHRASE -f ~/.ssh/$KEY_NAME -C $EMAIL
