#!/usr/bin/env bash
# bash to create RSA pair keys.

KEY_NAME="school"
KEY_BITS=4096
PASSPHRASE="betty"
EMAIL="memo12317emad@gmail.com"

ssh-keygen -t rsa -b $KEY_BITS -N $PASSPHRASE -f $KEY_NAME -C $EMAIL
